# titans/configs/model_configs/base.yaml
model:
  input_dim: 720
  memory_dim: 720
  num_memory_tokens: 32
  num_heads: 12
  num_layers: 4
  vocab_size: 50000
  
  sequence:
    max_length: 1024
    chunk_size: 512
    stride: 256

training:
  batch_size: 4
  learning_rate: 1e-4