# titans/configs/model_configs/experiment_config.yaml
_inherit: "base.yaml"  # Inherit from base configuration

model:
  # Experiment-specific modifications
  memory_dim: 896
  num_memory_tokens: 96
  
  neural_memory:
    momentum_factor: 0.95
    forget_factor: 0.05
    
training:
  batch_size: 24
  learning_rate: 8e-5
  warmup_steps: 2000