# titans/configs/default_config.yaml
model:
  name: "titans-mac"
  input_dim: 512       # Reduced from 768
  memory_dim: 512      # Reduced from 768
  num_memory_tokens: 32  # Reduced from 64
  num_heads: 8
  num_layers: 2
  dropout: 0.1
  vocab_size: 50000    # Added for token embedding
  
  # Memory configuration
  neural_memory:
    num_layers: 2
    momentum_factor: 0.9
    forget_factor: 0.1
    update_gate_bias: 1.0
    layer_norm_eps: 1e-5
    
  sequence:
    max_length: 1024   # Reduced from 8192
    chunk_size: 512    # Reduced
    stride: 256        # Reduced
    
  attention:
    head_dim: 64
    dropout: 0.1
    attention_dropout: 0.1

training:
  batch_size: 4        # Reduced from 32
  learning_rate: 1e-4
  weight_decay: 0.01
  max_epochs: 5
  warmup_steps: 1000
  gradient_clip: 1.0
  
  optimizer:
    type: "adamw"
    beta1: 0.9
    beta2: 0.999
    eps: 1e-8

validation:
  eval_steps: 1000
  save_steps: 5000
  max_checkpoints: 5
  eval_batch_size: 4   # Reduced